name: date_time_format
description: >-
  Utilities for formatting Dart's DateTime object using standard
  date/time notation or as a relative time offset.
version: 1.1.1
homepage: https://github.com/james-alex/date_time_format

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.2
