name: date_time_format
description: >-
  Utilities for formatting Dart's DateTime object using standard
  date/time notation or as a relative time offset.
version: 0.2.0-nullsafety
homepage: https://github.com/james-alex/date_time_format

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  pedantic: ^1.10.0-nullsafety.3
