name: date_time_format
description: >-
  Utilities for formatting Dart's DateTime object using standard
  date/time notation or as a relative time offset.
version: 2.0.0
homepage: https://github.com/james-alex/date_time_format

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
